"""initial schema

Revision ID: b8f91e555e30
Revises: 
Create Date: 2026-04-28 15:50:08.091589
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f91e555e30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_ts'), ['ts'], unique=False)

    op.create_table('backtest_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('cagr', sa.Float(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=False),
    sa.Column('sortino', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('median_oos_sharpe', sa.Float(), nullable=False),
    sa.Column('overfit_gap', sa.Float(), nullable=False),
    sa.Column('n_trades', sa.Integer(), nullable=False),
    sa.Column('passed_gate', sa.Integer(), nullable=False),
    sa.Column('gate_reason', sa.String(length=256), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_reports_spec_id'), ['spec_id'], unique=False)
        batch_op.create_index('ix_backtest_spec', ['spec_id', 'created_at'], unique=False)

    op.create_table('bot_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'symbol', name='uq_botposition_strategy_symbol')
    )
    with op.batch_alter_table('bot_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_positions_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bot_positions_symbol'), ['symbol'], unique=False)

    op.create_table('bot_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('paper_validated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_status_strategy_id'), ['strategy_id'], unique=True)

    op.create_table('congress_disclosures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=96), nullable=False),
    sa.Column('politician', sa.String(length=96), nullable=False),
    sa.Column('chamber', sa.String(length=16), nullable=False),
    sa.Column('party', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('amount_low', sa.Float(), nullable=False),
    sa.Column('amount_high', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('disclosure_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('congress_disclosures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_congress_disclosures_disclosure_date'), ['disclosure_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_congress_disclosures_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_congress_disclosures_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_congress_disclosures_politician'), ['politician'], unique=False)
        batch_op.create_index(batch_op.f('ix_congress_disclosures_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_congress_disclosures_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_snapshots_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_snapshots_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_equity_strategy_ts', ['strategy_id', 'ts'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=16), nullable=False),
    sa.Column('sentiment_model', sa.String(length=48), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_news_items_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_symbol'), ['symbol'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=False),
    sa.Column('client_order_id', sa.String(length=96), nullable=False),
    sa.Column('broker_order_id', sa.String(length=96), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('filled_qty', sa.Float(), nullable=False),
    sa.Column('filled_avg_price', sa.Float(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_client_order_id'), ['client_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index('ix_orders_strategy_ts', ['strategy_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_ts'), ['ts'], unique=False)

    op.create_table('research_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_research_doc_source_extid')
    )
    with op.batch_alter_table('research_documents', schema=None) as batch_op:
        batch_op.create_index('ix_research_doc_query', ['query_id', 'fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_documents_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_documents_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_documents_query_id'), ['query_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_documents_source'), ['source'], unique=False)

    op.create_table('research_findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('actionable', sa.Integer(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.create_index('ix_research_finding_query', ['query_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_findings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_findings_query_id'), ['query_id'], unique=False)

    op.create_table('research_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_queries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_queries_status'), ['status'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('acted', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ts'), ['ts'], unique=False)

    op.create_table('strategy_specs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('universe', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('bot_id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategy_specs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_specs_bot_id'), ['bot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_specs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_specs_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_specs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_specs_template_id'), ['template_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_version', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('notional', sa.Float(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index('ix_trades_strategy_ts', ['strategy_id', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_ts'), ['ts'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_ts'))
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index('ix_trades_strategy_ts')
        batch_op.drop_index(batch_op.f('ix_trades_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_trades_order_id'))

    op.drop_table('trades')
    with op.batch_alter_table('strategy_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_specs_template_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_specs_status'))
        batch_op.drop_index(batch_op.f('ix_strategy_specs_finding_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_specs_created_at'))
        batch_op.drop_index(batch_op.f('ix_strategy_specs_bot_id'))

    op.drop_table('strategy_specs')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ts'))
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_strategy_id'))

    op.drop_table('signals')
    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_queries_status'))
        batch_op.drop_index(batch_op.f('ix_research_queries_created_at'))

    op.drop_table('research_queries')
    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_findings_query_id'))
        batch_op.drop_index(batch_op.f('ix_research_findings_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_findings_category'))
        batch_op.drop_index('ix_research_finding_query')

    op.drop_table('research_findings')
    with op.batch_alter_table('research_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_documents_source'))
        batch_op.drop_index(batch_op.f('ix_research_documents_query_id'))
        batch_op.drop_index(batch_op.f('ix_research_documents_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_research_documents_external_id'))
        batch_op.drop_index('ix_research_doc_query')

    op.drop_table('research_documents')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_ts'))
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index('ix_orders_strategy_ts')
        batch_op.drop_index(batch_op.f('ix_orders_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_client_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_symbol'))
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_external_id'))

    op.drop_table('news_items')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_equity_strategy_ts')
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_ts'))
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_strategy_id'))

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('congress_disclosures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_congress_disclosures_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_congress_disclosures_symbol'))
        batch_op.drop_index(batch_op.f('ix_congress_disclosures_politician'))
        batch_op.drop_index(batch_op.f('ix_congress_disclosures_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_congress_disclosures_external_id'))
        batch_op.drop_index(batch_op.f('ix_congress_disclosures_disclosure_date'))

    op.drop_table('congress_disclosures')
    with op.batch_alter_table('bot_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_status_strategy_id'))

    op.drop_table('bot_status')
    with op.batch_alter_table('bot_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_bot_positions_strategy_id'))

    op.drop_table('bot_positions')
    with op.batch_alter_table('backtest_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_backtest_spec')
        batch_op.drop_index(batch_op.f('ix_backtest_reports_spec_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_reports_created_at'))

    op.drop_table('backtest_reports')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_events_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_kind'))

    op.drop_table('audit_events')
    # ### end Alembic commands ###
