"""add user_id to tenant-scoped tables

Revision ID: bbc1fea98ec9
Revises: b8f91e555e30
Create Date: 2026-04-28 15:55:42.719636
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc1fea98ec9'
down_revision: Union[str, None] = 'b8f91e555e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_audit_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('backtest_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_backtest_reports_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('bot_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_bot_positions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('bot_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_bot_status_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_equity_snapshots_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_research_findings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_research_queries_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_signals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('strategy_specs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_strategy_specs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=64), nullable=False, server_default='demo'))
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('strategy_specs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_specs_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('research_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_queries_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('research_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_findings_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('bot_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_status_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('bot_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_positions_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('backtest_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_reports_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
